server:
  port: 8081
spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/schedule?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
